### ISSUE TITLE
Add Test Coverage to all Projects

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/demonstrator#3]

**Comment by vonwenckstern** [comment]
Please add a configuration that the generated files in the target folder are not analyzed.
This destroys the entire code coverage metrics.

<img width="982" alt="bildschirmfoto 2017-10-28 um 02 03 50" src="https://user-images.githubusercontent.com/30497492/32129149-74bbcb80-bb84-11e7-89e9-6cf84ff97295.png">

**Comment by strepkov** [comment]
Finally I have found a way to specify packages, which have to be excluded from consideration. You can check it, but still several files from _symboltable exist. If it's really important, I can exclude them from coverage manually. P.S.: it's not possible with cobertura test coverage exclude upper level folder from consideration.

https://coveralls.io/github/EmbeddedMontiArc/EmbeddedMontiArc?branch=master

**Comment by ManuelSchrick** [comment]
The coverage Banner for the visualization project does not update itself.

**Comment by strepkov** [comment]
I have checked it now and the coverage on the badge the same like at the coveralls webpage. Or what do you mean? It may have some latency and does not response immediately.

**Comment by ManuelSchrick** [comment]
I meant the badge on this page:
[https://github.com/EmbeddedMontiArc/Documentation/blob/master/RepoStatus.md](https://github.com/EmbeddedMontiArc/Documentation/blob/master/RepoStatus.md)

The badge says the coverage is 32% but when i click on it it's actually 76%.

**Comment by strepkov** [comment]
<img width="1280" alt="screen shot 2017-11-11 at 11 18 15" src="https://user-images.githubusercontent.com/25662834/32688508-300cb96e-c6d2-11e7-87b8-53375a489627.png">

**Comment by strepkov** [comment]
Maybe just try another web-browser. Maybe your browser just cashed the images(badges)?

**Comment by ManuelSchrick** [comment]
I'm using chrome.
![repostatus](https://user-images.githubusercontent.com/30873727/32688533-ac12eb3c-c6d2-11e7-8e50-3a28d89307ff.png)

**Comment by ManuelSchrick** [comment]
Oh man, in another browser it works just fine...

**Comment by strepkov** [comment]
nice :) I suppose Chrome just cashed the Badges :)

**Comment by ManuelSchrick** [comment]
I just did some research and adding "&service=github" to the badge url might work. At least it did the trick for  the readme in the visualisation repo. Can you try that for that page too please? I don't have the rights to change that file and I refuse to use microsoft edge from now on :D

**Comment by strepkov** [comment]
done :)

**Comment by ManuelSchrick** [comment]
Awesome, now it's correct. Thank you! :)

**Comment by strepkov** [comment]
You are welcome. PS. now we know more about the Badges due to this problem :)

**Comment by vonwenckstern** [comment]
@strepkov Did you exclude the target folder for all projects, or only for EmbeddedMontiArc?

Because in NumberUnit, it also counts generated files:
https://coveralls.io/builds/14130977/source?filename=target%2Fgenerated-sources%2Fmonticore%2Fsourcecode%2Fsiunit%2Fmonticoresiunit%2Fsi%2F_visitor%2FCommonSIDelegatorVisitor.java

Maybe you can add the target ignore to every project

**Comment by vonwenckstern** [comment]
remove error messages done during test coverage creation in travis-ci log (suprress them)
```
net.sourceforge.cobertura.javancss.parser.ParseException: Encountered " ">" "> "" at line 147, column 27.
Was expecting one of:
    "assert" ...
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "enum" ...
    "false" ...
    "float" ...
    "int" ...
    "long" ...
    "new" ...
    "null" ...
    "short" ...
    "super" ...
    "this" ...
    "true" ...
    "void" ...
    <INTEGER_LITERAL> ...
    <FLOATING_POINT_LITERAL> ...
    <CHARACTER_LITERAL> ...
    <STRING_LITERAL> ...
    <IDENTIFIER> ...
    "(" ...
    "!" ...
    "~" ...
    "++" ...
    "--" ...
    "+" ...
    "-" ...
    
	at net.sourceforge.cobertura.javancss.parser.JavaParser.generateParseException(JavaParser.java:10490)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.jj_consume_token(JavaParser.java:10366)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.UnaryExpression(JavaParser.java:3175)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.MultiplicativeExpression(JavaParser.java:3090)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.AdditiveExpression(JavaParser.java:3085)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ShiftExpression(JavaParser.java:3027)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.RelationalExpression(JavaParser.java:2990)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.InstanceOfExpression(JavaParser.java:2977)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.AssigmentExpression(JavaParser.java:2959)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.EqualityExpression(JavaParser.java:2886)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.AndExpression(JavaParser.java:2860)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ExclusiveOrExpression(JavaParser.java:2843)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.InclusiveOrExpression(JavaParser.java:2826)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ConditionalAndExpression(JavaParser.java:2808)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ConditionalOrExpression(JavaParser.java:2790)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ConditionalExpression(JavaParser.java:2774)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Expression(JavaParser.java:2718)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ArgumentList(JavaParser.java:3620)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Arguments(JavaParser.java:3610)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.PrimarySuffix(JavaParser.java:3511)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.PrimaryExpression(JavaParser.java:3384)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.StatementExpression(JavaParser.java:4070)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Statement(JavaParser.java:3795)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.BlockStatement(JavaParser.java:3984)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Block(JavaParser.java:3934)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Statement(JavaParser.java:3765)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ForStatement(JavaParser.java:4445)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Statement(JavaParser.java:3815)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.BlockStatement(JavaParser.java:3984)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Block(JavaParser.java:3934)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.MethodDeclaration(JavaParser.java:1987)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassBodyDeclaration(JavaParser.java:1039)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassBody(JavaParser.java:898)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.UnmodifiedClassDeclaration(JavaParser.java:824)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassDeclaration(JavaParser.java:728)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.TypeDeclaration(JavaParser.java:575)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.CompilationUnit(JavaParser.java:318)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.parse(JavaParser.java:100)
	at net.sourceforge.cobertura.javancss.Javancss._measureSource(Javancss.java:192)
	at net.sourceforge.cobertura.javancss.Javancss._measureRoot(Javancss.java:268)
	at net.sourceforge.cobertura.javancss.Javancss.<init>(Javancss.java:347)
	at net.sourceforge.cobertura.javancss.JavancssFactory.newInstance(JavancssFactory.java:40)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getFunctionMetricsForSingleFile(ComplexityCalculator.java:243)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getAccumlatedCCNForSingleFile(ComplexityCalculator.java:143)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForSourceFileNameInternal(ComplexityCalculator.java:273)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForPackageInternal(ComplexityCalculator.java:208)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForProject(ComplexityCalculator.java:174)
	at net.sourceforge.cobertura.reporting.xml.XMLReport.<init>(XMLReport.java:70)
	at net.sourceforge.cobertura.reporting.xml.XMLReportFormatStrategy.save(XMLReportFormatStrategy.java:18)
	at net.sourceforge.cobertura.reporting.NativeReport.export(NativeReport.java:31)
	at net.sourceforge.cobertura.reporting.CompositeReport.export(CompositeReport.java:19)
	at net.sourceforge.cobertura.reporting.ReportMain.parseArgumentsAndReport(ReportMain.java:91)
	at net.sourceforge.cobertura.reporting.ReportMain.generateReport(ReportMain.java:141)
	at net.sourceforge.cobertura.reporting.ReportMain.main(ReportMain.java:151)
net.sourceforge.cobertura.javancss.parser.ParseException: Encountered " ">" "> "" at line 52, column 39.`
```
